version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2-cli-node-browsers

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get install -y libzip-dev
            sudo docker-php-ext-install zip pcntl
            wget http://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O php-cs-fixer
      - run:
          name: Install Composer dependencies
          command: |
            sudo composer self-update
            composer install -n --prefer-dist
            composer dump-autoload --optimize
      - run:
          name: Run syntax tests
          command: php php-cs-fixer fix --dry-run
      - run:
          name: Run unit tests
          command: php bin/phpunit
      - run:
          name: Clone E2E tests
          command: git clone https://github.com/contentful/the-example-app-e2e-tests.git ./tests-e2e
      - restore_cache:
          keys:
            - tea-e2e-tests-{{ checksum "./tests-e2e/package.json" }}
            - tea-e2e-tests
      - run:
          name: Install E2E tests dependencies
          command: |
            cd tests-e2e
            npm install
      - save_cache:
          key: tea-e2e-tests-{{ checksum "./tests-e2e/package.json" }}
          paths:
            - ./tests-e2e/node_modules
      - run:
          name: Run E2E tests
          command: |
            php bin/console --env=dev server:start 127.0.0.1:8000
            php bin/console --env=staging cache:warmup
            echo "APP_ENV=staging" > .env
            ./tests-e2e/node_modules/.bin/cypress run
