twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: App\Controller\ErrorController
    globals:
        state: "@App\\Service\\State"
        breadcrumb: "@App\\Service\\Breadcrumb"
        locale: "@App\\Service\\Locale"
