courses:
    path: /courses
    controller: App\Controller\CoursesController
    defaults: { tab: courses }

categories:
    path: /courses/categories
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults: { permanent: true, route: courses, keepQueryParams: true }

category:
    path: /courses/categories/{categorySlug}
    controller: App\Controller\CoursesController
    defaults: { tab: courses }

course:
    path: /courses/{courseSlug}
    controller: App\Controller\CourseController
    defaults: { tab: courses }

lessons:
    path: /courses/{courseSlug}/lessons
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults: { permanent: true, route: course, keepQueryParams: true }

lesson:
    path: /courses/{courseSlug}/lessons/{lessonSlug}
    controller: App\Controller\LessonController
    defaults: { tab: courses }

reset:
    path: /settings/reset
    controller: App\Controller\ResetController
    methods: [ POST ]

settings:
    path: /settings
    controller: App\Controller\SettingsController

imprint:
    path: /imprint
    controller: App\Controller\ImprintController

landing_page:
    path: /
    controller: App\Controller\LandingPageController
    defaults: { tab: home }

not_found:
    path: /{anything}
    controller: App\Controller\NotFoundController
    requirements: { anything: ".+" }
